### ISSUE TITLE
[webtools][models] click on Nothing to display generates an error

### ISSUE THREAD

**Issue by jcheron** [phpMv/ubiquity#130]
### Steps
With **Webtools**, in models part
click on **nothing to display** on any model which does not have any record. 
### Expected Result
No error
### Actual Result
it gives this error below.
```
Error

    Message : Uncaught ArgumentCountError: Too few arguments to function Ubiquity\controllers\admin\UbiquityMyAdminBaseController::_showModelDetails(), 0 passed in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php on line 148 and exactly 1 expected in C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php:359 Stack trace: #0 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(148): Ubiquity\controllers\admin\UbiquityMyAdminBaseController->_showModelDetails() #1 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(109): Ubiquity\controllers\Startup::runAction(Array, true, true) #2 C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(69): Ubiquity\controllers\Startup::forward('Admin/_showMode...') #3 C:\Php_Examples\default_nginx\.ubiquity\_index.php(18): Ubiquity\controllers\Startup::run(Array) #4 C:\Php_Examples\defaul
    File : C:\Php_Examples\default_nginx\vendor\phpmv\ubiquity-webtools\src\Ubiquity\controllers\admin\traits\ModelsTrait.php
    Line : 359
```

### Versions
- Ubiquity framework 2.3.10
- Ubiquity devtools 1.2.15
- php 7.4
- OS all

**Comment by jcheron** [comment]
@UlasSAYGINIM 
To be checked

**Comment by UlasSAYGINIM** [comment]
ok, there is no problem.
