### ISSUE TITLE
[console]  Ubiquity new blog creates project but when i run with 127.0.0.1:8099 it gives error

### ISSUE THREAD

**Issue by UlasSAYGINIM** [phpMv/ubiquity#195]
### Steps

i created a new project like documentation said
just run this command from command prompt on windows 10
 Ubiquity new blog

it created project but when i run Ubiquity serve -p:8099
it gives error.

### Expected Result
project should run.

### Actual Result
Fatal error: Uncaught TypeError: Typed property Ubiquity\cache\CacheManager::$annotationsEngine must be an instance of Ubiquity\annotations\AnnotationsEngineInterface, null used in C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\cache\traits\DevCacheTrait.php:38 Stack trace: #0 C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\core\Framework.php(83): Ubiquity\cache\CacheManager::getAnnotationsEngineInstance() #1 C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\core\postinstall\Display.php(36): Ubiquity\core\Framework::getAnnotationsEngine() #2 C:\PHP_Projects\blog\app\controllers\IndexController.php(15): Ubiquity\core\postinstall\Display::getPageInfos() #3 C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(172): controllers\IndexController->index() #4 C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(107): Ubiquity\controllers\Startup::runAction(Array, true, true) #5 C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.p in C:\PHP_Projects\blog\vendor\phpmv\ubiquity\src\Ubiquity\cache\traits\DevCacheTrait.php on line 38

### Versions

C:\PHP_Projects>Ubiquity new blog

  · Files copy...

    · Config files creation...

     ╭────────────────────────────────────────────────╮
     │      ■ info : Command line arguments           │
     │      · projectName='blog'                      │
     │      · cssFiles=''                             │
     │      · jsFiles=''                              │
     │      · injections=''                           │
     │      · dbName=''                               │
     │      · dbType='mysql'                          │
     │      · serverName='127.0.0.1'                  │
     │      · port='3306'                             │
     │      · user='root'                             │
     │      · password=''                             │
     │      · all-models=''                           │
     │      · admin=''                                │
     │      · themes=''                               │
     │      · siteUrl='http://127.0.0.1/blog/'        │
     │      · rewriteBase='blog'                      │
     ╰────────────────────────────────────────────────╯

    · Composer file creation...

Do you want to run composer install ? (y/n)
y
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 12 installs, 0 updates, 0 removals
  - Locking frameworks/jquery (2.1.4)
  - Locking mindplay/annotations (1.3.2)
  - Locking monolog/monolog (2.3.5)
  - Locking phpmailer/phpmailer (v6.5.4)
  - Locking phpmv/php-mv-ui (2.4.5)
  - Locking phpmv/ubiquity (2.4.11)
  - Locking phpmv/ubiquity-dev (0.0.23)
  - Locking phpmv/ubiquity-mailer (0.0.8)
  - Locking psr/log (1.1.4)
  - Locking symfony/polyfill-ctype (v1.24.0)
  - Locking symfony/polyfill-mbstring (v1.24.0)
  - Locking twig/twig (v3.3.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Downloading psr/log (1.1.4)
  - Downloading monolog/monolog (2.3.5)
  - Downloading phpmv/ubiquity-dev (0.0.23)
  - Downloading phpmailer/phpmailer (v6.5.4)
  - Downloading phpmv/ubiquity-mailer (0.0.8)
 0/5 [>---------------------------]   0%
 1/5 [=====>----------------------]  20%
 2/5 [===========>----------------]  40%
 3/5 [================>-----------]  60%
 5/5 [============================] 100%
  - Installing mindplay/annotations (1.3.2): Extracting archive
  - Installing psr/log (1.1.4): Extracting archive
  - Installing monolog/monolog (2.3.5): Extracting archive
  - Installing frameworks/jquery (2.1.4): Extracting archive
  - Installing phpmv/php-mv-ui (2.4.5): Extracting archive
  - Installing phpmv/ubiquity (2.4.11): Extracting archive
  - Installing phpmv/ubiquity-dev (0.0.23): Extracting archive
  - Installing symfony/polyfill-ctype (v1.24.0): Extracting archive
  - Installing phpmailer/phpmailer (v6.5.4): Extracting archive
  - Installing phpmv/ubiquity-mailer (0.0.8): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.24.0): Extracting archive
  - Installing twig/twig (v3.3.8): Extracting archive
  0/12 [>---------------------------]   0%
  3/12 [=======>--------------------]  25%
  6/12 [==============>-------------]  50%
  9/12 [=====================>------]  75%
 10/12 [=======================>----]  83%
 11/12 [=========================>--]  91%
 12/12 [============================] 100%
17 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
5 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
     ╭──────────────────────────────────────────────────────────────────╮
     │      ■ info : cache initialization                               │
     │      · cache directory is C:\PHP_Projects\blog\app\cache\        │
     ╰──────────────────────────────────────────────────────────────────╯
     ╭──────────────────────────────────────────────────╮
     │      ■ success : new-project                     │
     │      · project blog successfully created.        │
     ╰──────────────────────────────────────────────────╯

**Comment by UlasSAYGINIM** [comment]
I just applied what documentation says, did i miss any step on documentation? if i did , can you send url for it?
@jcheron thank you for information, i will try and tell the result later. i need time to look. now i am busy.
