### ISSUE TITLE
[ORM] model Table annotation

### ISSUE THREAD

**Issue by jyyan** [phpMv/ubiquity#39]
### Steps
Hello ,

ref as **[part] ORM Table annotation** #14

I got the 
`
@table("db_table_name")
`
work for me, but 
`@table("name"=>"db_table_name")`
is not work.

then i found that the [`TableAnnotation` L22](https://github.com/phpMv/ubiquity/blob/284fccf0b4af5da817e31a958b5b67844c459b10/src/Ubiquity/annotations/TableAnnotation.php#L22) only check & take the array $properties[0] as annotation name. but missing to check map $properties['name'] 

when i patch with below it work fine for me
```php
/**
* Initialize the annotation.
*/
public function initAnnotation(array $properties) {
    error_log(var_export($properties, true));
    /*
        array (
        'name' => 'db_table_name',
        )
    */
    if (isset ( $properties [0] )) {
        $this->name = $properties [0];
        unset ( $properties [0] );
    } else if (isset ( $properties ['name'] )) {
        $this->name = $properties ['name'];
        unset ( $properties ['name'] );
    } else {
        throw new \Exception ( 'Table annotation must have a name' );
    }
}
```

### Actual Result
```php
PHP Fatal error:  Uncaught Exception: Table annotation must have a name in /vendor/phpmv/ubiquity/src/Ubiquity/annotations/TableAnnotation.php:27
Stack trace:
#0 /vendor/mindplay/annotations/src/annotations/AnnotationManager.php(296): Ubiquity\annotations\TableAnnotation->initAnnotation(Array)
#1 /vendor/mindplay/annotations/src/annotations/AnnotationManager.php(263): mindplay\annotations\AnnotationManager->getAnnotations('models\\Sys_logs', 'class')
#2 /vendor/mindplay/annotations/src/annotations/AnnotationManager.php(594): mindplay\annotations\AnnotationManager->getAnnotations('models\\Sys_logs', 'property', '$id')
#3 /vendor/mindplay/annotations/src/annotations/Annotations.php(90): mindplay\annotations\AnnotationManager->getPropertyAnnotations('models\\S in /vendor/phpmv/ubiquity/src/Ubiquity/annotations/TableAnnotation.php on line 27

```
### Versions

· PHP 7.1.27-1+ubuntu18.04.1+deb.sury.org+1
· Ubiquity devtools (1.2.3)
· Ubiquity 2.1.2

**Comment by jcheron** [comment]
Hi @jyyan ,
Can you make a PR with these modifications?
note:
You can remove the line:
```php
unset ( $properties ['name']);
```
useless

**Comment by jyyan** [comment]
thanks @jcheron
