### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: Return value of Ubiquity\controllers\Startup::getControllerInstance() must be 

### ISSUE THREAD

**Issue by vnt** [phpMv/ubiquity#80]
I'm trying Ubiquity for the first time.
When I launch the command **Ubiquity serve** I get the following error

    · The project folder is /Users/vnt/Sites/ubi/quick-start

    · Starting php server at 127.0.0.1:8090...
    · Press Ctrl+C to stop it!

[Wed Oct 30 09:39:12 2019] PHP Fatal error:  Uncaught TypeError: Return value of Ubiquity\controllers\Startup::getControllerInstance() must be an instance of Ubiquity\controllers\object, instance of controllers\IndexController returned in /Users/vnt/Sites/ubi/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php:49
Stack trace:
#0 /Users/vnt/Sites/ubi/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(142): Ubiquity\controllers\Startup::getControllerInstance('controllers\\Ind...')
#1 /Users/vnt/Sites/ubi/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(102): Ubiquity\controllers\Startup::runAction(Array, true, true)
#2 /Users/vnt/Sites/ubi/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php(72): Ubiquity\controllers\Startup::forward('_default')
#3 /Users/vnt/Sites/ubi/quick-start/.ubiquity/_index.php(18): Ubiquity\controllers\Startup::run(Array)
#4 /Users/vnt/Sites/ubi/quick-start/.ubiquity/.htrouter.php(5): include_once('/ in /Users/vnt/Sites/ubi/quick-start/vendor/phpmv/ubiquity/src/Ubiquity/controllers/Startup.php on line 49

What should I do to solve the problem?

### Versions
- Ubiquity framework 2.3
- Ubiquity devtools 1.2.10
- php 7.1.14
- OS Mac OS X 10.14.6

**Comment by jcheron** [comment]
Hi @vnt ,
The latest version of Ubiquity introduced the PHP type hinting.
The `getControllerInstance` method of `Startup` must return an `object`.
But the `object` return type only exists since PHP 7.2+ (see https://mlocati.github.io/articles/php-type-hinting.html)
To solve your problem:
- or you can go back to version 2.3.1 of Ubiquity: ` composer require phpmv/ubiquity:2.3.1`
- Either you switch to `PHP 7.3`

**Comment by jcheron** [comment]
No activity for 3 weeks -> closed
